version: '3'

services:
  java-runner:
    image: [image name]
    deploy:
      #number of replicas required
      replicas: 5
    ports:
    #port mapping 
      - 8081:8081
  #visualizer is optional, provides GUI showing container status
  #more details can be found here - https://github.com/dockersamples/docker-swarm-visualizer
  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 8082:8082
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
